version: '3.8'
services:
  postgresql:
    image: postgres:15.4
    container_name: ${POSTGRES_SERVER:-postgresql}
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-animals_share}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_net

  backend:
    container_name: backend
    build:
      context: ./animals
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_SERVER: ${POSTGRES_SERVER:-postgresql}
      POSTGRES_DB: ${POSTGRES_DB:-animals_share}
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    depends_on:
      - postgresql
    networks:
      - postgres_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_animals
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@admin.org}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-password}
    depends_on:
      - postgresql
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data
    networks:
      - postgres_net


networks:
  postgres_net:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: